# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PhoneNumber(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, formatted_phone_number: str = None):  # noqa: E501
        """PhoneNumber - a model defined in Swagger

        :param formatted_phone_number: The formatted_phone_number of this PhoneNumber.  # noqa: E501
        :type formatted_phone_number: str
        """
        self.swagger_types = {"formatted_phone_number": str}

        self.attribute_map = {"formatted_phone_number": "formatted_phone_number"}
        self._formatted_phone_number = formatted_phone_number

    @classmethod
    def from_dict(cls, dikt) -> "PhoneNumber":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhoneNumber of this PhoneNumber.  # noqa: E501
        :rtype: PhoneNumber
        """
        return util.deserialize_model(dikt, cls)

    @property
    def formatted_phone_number(self) -> str:
        """Gets the formatted_phone_number of this PhoneNumber.


        :return: The formatted_phone_number of this PhoneNumber.
        :rtype: str
        """
        return self._formatted_phone_number

    @formatted_phone_number.setter
    def formatted_phone_number(self, formatted_phone_number: str):
        """Sets the formatted_phone_number of this PhoneNumber.


        :param formatted_phone_number: The formatted_phone_number of this PhoneNumber.
        :type formatted_phone_number: str
        """

        self._formatted_phone_number = formatted_phone_number
