openapi: 3.0.3
info:
  title: Fine Phone Number Service
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /getphonenumber:
    get:
      summary: Finds phone_number from address
      operationId: find_phone_number
      parameters:
      - name: address
        in: query
        description: address for query and getting phone_number
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: Computer History Museum Mountain View USA
      responses:
        "200":
          description: None empty address for querry to service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneNumber'
        "500":
          description: Internal Server Error
        "400":
          description: Address is not valid
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    PhoneNumber:
      type: object
      properties:
        formatted_phone_number:
          type: string
          example: (650) 810-1010
      example:
        formatted_phone_number: (650) 810-1010

